s = "  Hello World from Python  "
print("Original string:")
print(repr(s))
print("-" * 50)
print("upper():", s.upper())
print("lower():",s.lower()) 
print("title():",s.title()) 
print("capitalize():",s.capitalize())
print("swapcase():",s.swapcase())
print("-" * 50)
print("strip():", s.strip()) 
print("lstrip():", s.lstrip())
print("rstrip():", s.rstrip())
print("-" * 50)
print("find('World'):",s.find("World"))
print("rfind('o'):",s.rfind("o"))
print("count('o'):",s.count("o")) 
print("startswith('  Hello'):", s.startswith("  Hello")) 
print("endswith('Python  '),",s.endswith("Python  "))
print("-" * 50)
print("replace('World', 'Everyone'):",s.replace("World", "Everyone"))
print("-" * 50)
words = s.split()
print("split():", words)
print("' '.join(words):", " ".join(words))
print("split('o'):", s.split("o"))
print("-" * 50)
text = "Python" 
print("center(20, ''):", text.center(20, ""))
print("ljust(20, '-'):", text.ljust(20, "-")) 
print("rjust(20, '-'):", text.rjust(20, "-"))
print("zfill(10):", text.zfill(10))
print("-" * 50)
print("isalnum():", "Python3".isalnum())
print("isalpha():", "Python".isalpha())
print("isdigit():", "12345".isdigit())
print("islower():", "python".islower()) 
print("isupper():", "PYTHON".isupper()) 
print("isspace():", "   ".isspace()) 
print("istitle():", "Hello World".istitle())
print("-" * 50)
encoded = "Python".encode('utf-8')
print("encode():", encoded) 
print("decode():", encoded.decode('utf-8'))
print("-" * 50)
name = "Shital" 
age = 20
print("format():", "My name is {} and age is {}".format(name, age)) 
print("f-string:", f"My name is {name} and age is {age}")
print("-" * 50)
line = "one,two,three"
print("partition(','):", line.partition(",")) 
print("rpartition(','):", line.rpartition(",")) 
print("splitlines():", "Hello\nWorld".splitlines())
print("-" * 50)
url = "https://example.com"
print("removeprefix('https://'):", url.removeprefix("https://")) 
print("removesuffix('.com'):", url.removesuffix(".com"))
print("-" * 50) 
print("End of string methods demo")

